services:
  backend:
    build:
      context: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/app
      - ./app/uploads:/app/uploads
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://192.168.1.5:8080
    depends_on:
      - backend